CREATE TABLE samples(Specimen varchar(255) NOT NULL,Bio_Project varchar(255)  NOT NULL,Material  varchar(255) NOT NULL,Specimen_Collected_Date Date NOT NULL,Sequence_Read_Archive varchar(255) NOT NULL,Bio_Sample varchar(255) NOT NULL,Lineage varchar(255) NOT NULL,Octal_Spoligotype varchar(255) NOT NULL, PRIMARY KEY (Specimen));

CREATE TABLE lowenstein(Specimen varchar(255) NOT NULL, Date date, H varchar(255) NOT NULL, R varchar(255) NOT NULL, S varchar(255) NOT NULL, E varchar(255) NOT NULL, Ofx varchar(255) NOT NULL, Cm varchar(255) NOT NULL, Am varchar(255) NOT NULL, Km varchar(255) NOT NULL, Z varchar(255) NOT NULL, Lfx varchar(255) NOT NULL, Mfx varchar(255) NOT NULL, Pas varchar(255) NOT NULL, Pto varchar(255) NOT NULL, Cs varchar(255) NOT NULL, Amx_Clv varchar(255) NOT NULL, Mb varchar(255) NOT NULL, Dld varchar(255) NOT NULL, Bdq varchar(255) NOT NULL, Ipm_Cln varchar(255) NOT NULL, Lzd varchar(255) NOT NULL, Cfz varchar(255) NOT NULL, Clr varchar(255) NOT NULL, Ft varchar(255) NOT NULL, AG_CP varchar(255) NOT NULL, Action varchar(255) NOT NULL, PRIMARY KEY (Specimen));

CREATE TABLE hain (Specimen varchar(255) NOT NULL, Date date, H varchar(255) NOT NULL, R varchar(255) NOT NULL, S varchar(255) NOT NULL, E varchar(255) NOT NULL, Ofx varchar(255) NOT NULL, Cm varchar(255) NOT NULL, Am varchar(255) NOT NULL, Km varchar(255) NOT NULL, Z varchar(255) NOT NULL, Lfx varchar(255) NOT NULL, Mfx varchar(255) NOT NULL, Pas varchar(255) NOT NULL, Pto varchar(255) NOT NULL, Cs varchar(255) NOT NULL, Amx_Clv varchar(255) NOT NULL, Mb varchar(255) NOT NULL, Dld varchar(255) NOT NULL, Bdq varchar(255) NOT NULL, Ipm_Cln varchar(255) NOT NULL, Lzd varchar(255) NOT NULL, Cfz varchar(255) NOT NULL, Clr varchar(255) NOT NULL, Ft varchar(255) NOT NULL, AG_CP varchar(255) NOT NULL, Action varchar(255) NOT NULL, PRIMARY KEY (Specimen));

CREATE TABLE bactec(Specimen varchar(255) NOT NULL, Date date, H varchar(255) NOT NULL, R varchar(255) NOT NULL, S varchar(255) NOT NULL, E varchar(255) NOT NULL, Ofx varchar(255) NOT NULL, Cm varchar(255) NOT NULL, Am varchar(255) NOT NULL, Km varchar(255) NOT NULL, Z varchar(255) NOT NULL, Lfx varchar(255) NOT NULL, Mfx varchar(255) NOT NULL, Pas varchar(255) NOT NULL, Pto varchar(255) NOT NULL, Cs varchar(255) NOT NULL, Amx_Clv varchar(255) NOT NULL, Mb varchar(255) NOT NULL, Dld varchar(255) NOT NULL, Bdq varchar(255) NOT NULL, Ipm_Cln varchar(255) NOT NULL, Lzd varchar(255) NOT NULL, Cfz varchar(255) NOT NULL, Clr varchar(255) NOT NULL, Ft varchar(255) NOT NULL, AG_CP varchar(255) NOT NULL, Action varchar(255) NOT NULL, PRIMARY KEY (Specimen));

CREATE TABLE genxpert(Specimen varchar(255) NOT NULL, Date date, H varchar(255) NOT NULL, R varchar(255) NOT NULL, S varchar(255) NOT NULL, E varchar(255) NOT NULL, Ofx varchar(255) NOT NULL, Cm varchar(255) NOT NULL, Am varchar(255) NOT NULL, Km varchar(255) NOT NULL, Z varchar(255) NOT NULL, Lfx varchar(255) NOT NULL, Mfx varchar(255) NOT NULL, Pas varchar(255) NOT NULL, Pto varchar(255) NOT NULL, Cs varchar(255) NOT NULL, Amx_Clv varchar(255) NOT NULL, Mb varchar(255) NOT NULL, Dld varchar(255) NOT NULL, Bdq varchar(255) NOT NULL, Ipm_Cln varchar(255) NOT NULL, Lzd varchar(255) NOT NULL, Cfz varchar(255) NOT NULL, Clr varchar(255) NOT NULL, Ft varchar(255) NOT NULL, AG_CP varchar(255) NOT NULL, Action varchar(255) NOT NULL, PRIMARY KEY (Specimen));

CREATE TABLE dst(Specimen varchar(255) NOT NULL, Date date, H varchar(255) NOT NULL, R varchar(255) NOT NULL, S varchar(255) NOT NULL, E varchar(255) NOT NULL, Ofx varchar(255) NOT NULL, Cm varchar(255) NOT NULL, Am varchar(255) NOT NULL, Km varchar(255) NOT NULL, Z varchar(255) NOT NULL, Lfx varchar(255) NOT NULL, Mfx varchar(255) NOT NULL, Pas varchar(255) NOT NULL, Pto varchar(255) NOT NULL, Cs varchar(255) NOT NULL, Amx_Clv varchar(255) NOT NULL, Mb varchar(255) NOT NULL, Dld varchar(255) NOT NULL, Bdq varchar(255) NOT NULL, Ipm_Cln varchar(255) NOT NULL, Lzd varchar(255) NOT NULL, Cfz varchar(255) NOT NULL, Clr varchar(255) NOT NULL, Ft varchar(255) NOT NULL, AG_CP varchar(255) NOT NULL, Action varchar(255) NOT NULL, PRIMARY KEY (Specimen));



LOAD DATA LOCAL INFILE 'samples.csv' INTO TABLE samples FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 ROWS;
LOAD DATA LOCAL INFILE 'Lowenstein-Jensen.csv' INTO TABLE lowenstein FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 ROWS;
LOAD DATA LOCAL INFILE 'Hain.csv' INTO TABLE hain FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 ROWS;
LOAD DATA LOCAL INFILE 'DST.csv' INTO TABLE dst FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 ROWS;
LOAD DATA LOCAL INFILE 'Bactec.csv' INTO TABLE bactec FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 ROWS;
LOAD DATA LOCAL INFILE 'GeneXpert.csv' INTO TABLE genxpert FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 ROWS;
